before:
  hooks:
  - make goreleaser_hook
builds:
  - 
    main: ./cmd/prom-isi-exporter.go
    env:
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
    - README.md
    - CHANGELOG.md
    - LICENSE 
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'