# B"H
# Configmap to add environment variables from values.yaml in use in helpers.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val }}
  {{- end}}